import fs from 'node:fs';import path from 'node:path';import Papa from 'papaparse';import type {Analysis,Category,Fund,Holding,PortfolioAnalysis,Position,ExposurePath} from './types.js';
const root=path.resolve(process.cwd(),'server/data');
const funds:Fund[]=JSON.parse(fs.readFileSync(path.join(root,'funds.json'),'utf8'));
const screens:{ticker:string;categories:Category[];evidence:string;source:string}[]=JSON.parse(fs.readFileSync(path.join(root,'controversies.json'),'utf8'));
const screenMap=new Map(screens.map(x=>[x.ticker,x]));
export function getFunds(){return funds}
export function loadHoldings(ticker:string):Holding[]{
 const raw=fs.readFileSync(path.join(root,'holdings',`${ticker}.csv`),'utf8');const header=raw.indexOf('Ticker,Name,Sector');if(header<0)throw new Error('Holdings header not found');
 const parsed=Papa.parse<Record<string,string>>(raw.slice(header),{header:true,skipEmptyLines:true});
 return parsed.data.filter(x=>x['Asset Class']==='Equity'&&Number(x['Weight (%)'])>0).map(x=>{const s=screenMap.get(x.Ticker);return {ticker:x.Ticker,name:x.Name,sector:x.Sector,weight:Number(x['Weight (%)']),categories:s?.categories??[],evidence:s?.evidence,source:s?.source}}).sort((a,b)=>b.weight-a.weight);
}
export function analyzeFund(ticker:string):Analysis{const fund=funds.find(f=>f.ticker===ticker.toUpperCase());if(!fund)throw new Error('Unsupported fund');const holdings=loadHoldings(fund.ticker);const categories:Category[]=['Fossil fuels','Weapons','Private prisons','Tobacco','Deforestation'];const categoryExposure=categories.map(category=>({category,weight:+holdings.filter(h=>h.categories.includes(category)).reduce((n,h)=>n+h.weight,0).toFixed(2)}));const flagged=holdings.filter(h=>h.categories.length);return {fund,holdings,categoryExposure,flaggedWeight:+flagged.reduce((n,h)=>n+h.weight,0).toFixed(2),flaggedCount:flagged.length,coverageWeight:+holdings.reduce((n,h)=>n+h.weight,0).toFixed(2),alternatives:funds.filter(f=>f.ticker!==fund.ticker&&f.kind==='ESG screened').sort((a,b)=>Math.abs(a.return3y-fund.return3y)-Math.abs(b.return3y-fund.return3y))};}
export function simulateSwap(source:Analysis,target:Analysis,amount:number){return {amount,sourceExposure:+(amount*source.flaggedWeight/100).toFixed(2),targetExposure:+(amount*target.flaggedWeight/100).toFixed(2),reduction:+(amount*(source.flaggedWeight-target.flaggedWeight)/100).toFixed(2)};}

export function analyzePortfolio(positions:Position[]):PortfolioAnalysis{
 const clean=positions.filter(p=>p.ticker?.trim()&&Number.isFinite(p.amount)&&p.amount>0).map(p=>({ticker:p.ticker.trim().toUpperCase(),amount:p.amount}));
 if(!clean.length)throw new Error('Add at least one positive position');
 const totalAmount=clean.reduce((n,p)=>n+p.amount,0);const allStocks=new Map<string,Holding>();
 for(const fund of funds)for(const holding of loadHoldings(fund.ticker))if(!allStocks.has(holding.ticker))allStocks.set(holding.ticker,holding);
 const dollars=new Map<string,{base:Holding;amount:number}>();const exposurePaths:ExposurePath[]=[];const unknownTickers:string[]=[];let analyzedAmount=0;let positionsAnalyzed=0;
 for(const position of clean){const fund=funds.find(f=>f.ticker===position.ticker);const stock=allStocks.get(position.ticker);if(fund){positionsAnalyzed++;analyzedAmount+=position.amount;for(const h of loadHoldings(fund.ticker)){const value=position.amount*h.weight/100;if(h.categories.length)exposurePaths.push({positionTicker:position.ticker,positionAmount:position.amount,fundWeight:h.weight,companyTicker:h.ticker,companyName:h.name,companyDollars:+value.toFixed(2),portfolioWeight:+(value/totalAmount*100).toFixed(3),categories:h.categories,source:h.source,evidence:h.evidence});const prev=dollars.get(h.ticker);dollars.set(h.ticker,{base:h,amount:(prev?.amount??0)+value})}}else if(stock){positionsAnalyzed++;analyzedAmount+=position.amount;if(stock.categories.length)exposurePaths.push({positionTicker:position.ticker,positionAmount:position.amount,fundWeight:100,companyTicker:stock.ticker,companyName:stock.name,companyDollars:+position.amount.toFixed(2),portfolioWeight:+(position.amount/totalAmount*100).toFixed(3),categories:stock.categories,source:stock.source,evidence:stock.evidence});const prev=dollars.get(stock.ticker);dollars.set(stock.ticker,{base:stock,amount:(prev?.amount??0)+position.amount})}else unknownTickers.push(position.ticker)}
 const holdings=[...dollars.values()].map(x=>({...x.base,weight:+(x.amount/totalAmount*100).toFixed(2)})).sort((a,b)=>b.weight-a.weight);
 const categories:Category[]=['Fossil fuels','Weapons','Private prisons','Tobacco','Deforestation'];const categoryExposure=categories.map(category=>{const amount=[...dollars.values()].filter(x=>x.base.categories.includes(category)).reduce((n,x)=>n+x.amount,0);return {category,weight:+(amount/totalAmount*100).toFixed(2),dollars:+amount.toFixed(2)}});const flagged=[...dollars.values()].filter(x=>x.base.categories.length);const flaggedDollars=flagged.reduce((n,x)=>n+x.amount,0);
 return {totalAmount:+totalAmount.toFixed(2),analyzedAmount:+analyzedAmount.toFixed(2),coveragePercent:+(analyzedAmount/totalAmount*100).toFixed(1),positionsAnalyzed,unknownTickers,holdings,categoryExposure,flaggedWeight:+(flaggedDollars/totalAmount*100).toFixed(2),flaggedDollars:+flaggedDollars.toFixed(2),flaggedCount:flagged.length,exposurePaths:exposurePaths.sort((a,b)=>b.companyDollars-a.companyDollars)};
}
