import {useEffect,useMemo,useState} from 'react';import {ArrowRight,BarChart3,Database,Leaf,Search,ShieldCheck,Sparkles,TrendingUp} from 'lucide-react';import {Bar,BarChart,CartesianGrid,Cell,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';import {api} from './lib/api';import type {Analysis,Fund} from './types';import PortfolioBuilder from './components/PortfolioBuilder';
const colors=['#ef7c58','#d95b73','#7c65d6','#d8a434','#36a27e'];
const money=new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0});
function App(){const [funds,setFunds]=useState<Fund[]>([]);const [ticker,setTicker]=useState('IVV');const [analysis,setAnalysis]=useState<Analysis>();const [loading,setLoading]=useState(true);const [amount,setAmount]=useState(10000);const [target,setTarget]=useState('SUSA');const [targetResult,setTargetResult]=useState<Analysis>();
 const run=async(t=ticker)=>{setLoading(true);setAnalysis(await api.analyze(t));setTicker(t);setLoading(false)};
 useEffect(()=>{Promise.all([api.funds(),api.analyze('IVV'),api.analyze('SUSA')]).then(([f,a,t])=>{setFunds(f);setAnalysis(a);setTargetResult(t);setLoading(false)})},[]);useEffect(()=>{api.analyze(target).then(setTargetResult)},[target]);
 const targetAnalysis=useMemo(()=>funds.find(f=>f.ticker===target),[funds,target]);const targetExposure=targetResult?.flaggedWeight??0;const sourceDollars=amount*(analysis?.flaggedWeight??0)/100;const targetDollars=amount*targetExposure/100;
 return <div className="app"><nav><div className="brand"><span className="mark"><Leaf size={19}/></span>ClearHold</div><div className="navlinks"><a href="#analysis">Fund X-ray</a><a href="#portfolio">Portfolio</a><a href="#method">Methodology</a><span className="badge"><span/> Fixture data</span></div></nav>
 <main><section className="hero"><div className="eyebrow"><Sparkles size={14}/> INVESTMENT TRANSPARENCY</div><h1>You know what you invest.<br/><em>Do you know what you own?</em></h1><p>Look through an ETF, spot values-based exposure, and compare a cleaner alternative without hiding the tradeoffs.</p><div className="search"><Search size={21}/><select aria-label="Fund ticker" value={ticker} onChange={e=>setTicker(e.target.value)}>{funds.map(f=><option key={f.ticker}>{f.ticker}</option>)}</select><span>{funds.find(f=>f.ticker===ticker)?.name}</span><button onClick={()=>run()}>Analyze fund <ArrowRight size={17}/></button></div><div className="trust"><span><Database size={15}/> Public issuer holdings</span><span><ShieldCheck size={15}/> Traceable screen rules</span><span><BarChart3 size={15}/> Side-by-side tradeoffs</span></div></section>
 {loading||!analysis?<div className="loading">Opening the fund...</div>:<section id="analysis" className="dashboard"><div className="sectionhead"><div><span className="kicker">PORTFOLIO X-RAY</span><h2>{analysis.fund.ticker} <small>{analysis.fund.name}</small></h2></div><div className="asof">Holdings as of <b>{analysis.fund.asOf}</b><br/>{analysis.coverageWeight.toFixed(1)}% of fund weight parsed</div></div>
 <div className="metrics"><div className="metric warning"><span>FLAGGED EXPOSURE</span><strong>{analysis.flaggedWeight.toFixed(2)}%</strong><small>Across {analysis.flaggedCount} screened holdings</small></div><div className="metric"><span>3-YEAR RETURN</span><strong>{analysis.fund.return3y.toFixed(2)}%</strong><small>Annualized total return</small></div><div className="metric"><span>3-YEAR VOLATILITY</span><strong>{analysis.fund.volatility3y.toFixed(2)}%</strong><small>Annualized standard deviation</small></div><div className="metric"><span>EXPENSE RATIO</span><strong>{analysis.fund.expenseRatio.toFixed(2)}%</strong><small>Per year</small></div></div>
 <div className="grid"><article className="card chartcard"><div className="cardhead"><div><h3>Exposure by screen</h3><p>Percent of your fund tied to each category</p></div></div><div className="chart"><ResponsiveContainer><BarChart data={analysis.categoryExposure} layout="vertical" margin={{left:20,right:25}}><CartesianGrid strokeDasharray="3 3" horizontal={false}/><XAxis type="number" unit="%"/><YAxis dataKey="category" type="category" width={92} tick={{fontSize:12}}/><Tooltip formatter={(v)=>`${v}%`}/><Bar dataKey="weight" radius={[0,7,7,0]}>{analysis.categoryExposure.map((_,i)=><Cell fill={colors[i]} key={i}/>)}</Bar></BarChart></ResponsiveContainer></div></article>
 <article className="card offenders"><div className="cardhead"><div><h3>Largest flagged holdings</h3><p>Ranked by your dollars exposed</p></div></div>{analysis.holdings.filter(h=>h.categories.length).slice(0,6).map((h,i)=><div className="holding" key={h.ticker}><span className="rank">{i+1}</span><div className="company"><b>{h.name}</b><small>{h.ticker} · {h.categories.join(', ')}</small></div><div className="weight"><b>{h.weight.toFixed(2)}%</b><small>{money.format(amount*h.weight/100)} of {money.format(amount)}</small></div></div>)}</article></div>
 <section className="swap"><div className="swapintro"><span className="kicker">SWAP SIMULATOR</span><h2>What changes if you switch?</h2><p>Compare the values exposure and financial profile. This is a model, not a recommendation.</p><label>Amount invested<div className="amount"><span>$</span><input aria-label="Investment amount" type="number" value={amount} onChange={e=>setAmount(Math.max(0,Number(e.target.value)))}/></div></label></div><div className="compare"><div className="fundbox current"><span>CURRENT</span><h3>{analysis.fund.ticker}</h3><p>{analysis.fund.name}</p><dl><div><dt>Flagged dollars</dt><dd>{money.format(sourceDollars)}</dd></div><div><dt>3-year return</dt><dd>{analysis.fund.return3y}%</dd></div><div><dt>Volatility</dt><dd>{analysis.fund.volatility3y}%</dd></div><div><dt>Fee</dt><dd>{analysis.fund.expenseRatio}%</dd></div></dl></div><div className="arrow"><ArrowRight/></div><div className="fundbox alternative"><span>ALTERNATIVE</span><select value={target} onChange={e=>setTarget(e.target.value)}>{analysis.alternatives.map(f=><option key={f.ticker}>{f.ticker}</option>)}</select><p>{targetAnalysis?.name}</p><dl><div><dt>Flagged dollars</dt><dd>{money.format(targetDollars)}</dd></div><div><dt>3-year return</dt><dd>{targetAnalysis?.return3y}%</dd></div><div><dt>Volatility</dt><dd>{targetAnalysis?.volatility3y}%</dd></div><div><dt>Fee</dt><dd>{targetAnalysis?.expenseRatio}%</dd></div></dl></div><div className="impact"><Leaf/><span>SCREENED EXPOSURE CHANGE</span><strong>{sourceDollars>=targetDollars?"-":"+"}{money.format(Math.abs(sourceDollars-targetDollars))}</strong><small>on a {money.format(amount)} position</small></div><div className="category-compare"><b>Category exposure, current → alternative</b>{analysis.categoryExposure.map((x,i)=><span key={x.category}>{x.category}<strong>{x.weight}% → {targetResult?.categoryExposure[i]?.weight??0}%</strong></span>)}<small>Past financial metrics and screen exposure are shown independently. Lower exposure does not mean a fund is a better investment.</small></div></div></section>
 <PortfolioBuilder/><section id="method" className="method"><div><span className="kicker">BUILT FOR TRANSPARENCY</span><h2>No mystery score.</h2><p>ClearHold reports observable exposure, not a one-number ESG grade. Holdings snapshots were captured September 16, 2026; financial metrics are trailing, not forecasts. An unflagged company is not necessarily controversy-free.</p><div className="source-links"><a href="https://www.ishares.com/us" target="_blank">iShares holdings</a><a href="https://www.sipri.org/databases/armsindustry" target="_blank">SIPRI weapons data</a><a href="https://www.epa.gov/ghgreporting" target="_blank">EPA GHGRP</a><a href="https://forest500.org/forest-500-data-methods/" target="_blank">Forest 500</a></div></div><div className="methodgrid"><div><Database/><h3>Real holdings</h3><p>Committed snapshots from official iShares downloads keep the demo reproducible offline.</p></div><div><ShieldCheck/><h3>Named evidence</h3><p>Each match maps to a source-backed category and a short reason.</p></div><div><TrendingUp/><h3>Financial context</h3><p>Return, volatility, and fees stay beside the values comparison.</p></div></div></section></section>}
 </main><footer><div className="brand"><span className="mark"><Leaf size={17}/></span>ClearHold</div><p>Educational screening prototype. Not investment advice.</p><a href="#method">Data & methodology</a></footer></div>}
export default App;
